---
# Lookup tasks file for ansible-role-tidal-agent

- name: "Check for JAVA_HOME Environment Variable"
  ansible.builtin.shell:
    cmd: . /etc/profile && (env | grep -iP "JAVA_HOME")
  register: result
  ignore_errors: true

- debug:
    var: result

- name: "Set Facts for JAVA_HOME Environment Variable"
  ansible.builtin.set_fact:
    java_home: "{{ result.stdout | split('=') | last }}"
  when:
    - result.rc == 0
    - not result.failed | bool

- name: "Set Facts for Java Installed variable"
  ansible.builtin.set_fact:
    java_installed: false
  when:
    - java_home is not defined
    #- result.failed is true

- name: "Check for Tidal Home directory"
  ansible.builtin.stat:
    path: /opt/TIDAL/Agent/
  register: result
  ignore_errors: true

- name: "Set Facts for Tidal Home directory"
  ansible.builtin.set_fact:
    tidal_home: /opt/TIDAL/Agent/
  when:
    - result.stat.exists
    - result.stat.isdir
    - not result.failed | bool
    #- result.failed is false

- name: "Set Facts for Install variable"
  ansible.builtin.set_fact:
    install: true
  when:
    - tidal_home is not defined


