---
# tasks file for ansible-role-tidal-agent

- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: "Install Python PExpect module"
  block:
    - name: "Install expect, if not already installed (RHEL7)"
      ansible.builtin.package:
        name: "expect"
      when:
        - '"expect" not in ansible_facts.packages'
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version <= '7'
    - name: "Install Pexpect Python module, if not already installed (RHEL8)"
      ansible.builtin.package:
        name: "python3-pexpect"
      when:
        - '"python3-pexpect" not in ansible_facts.packages'
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version == '8'

- name: "Install Java Development Kit (OpenJDK)"
  block:
    - name: "Install Java Development Kit (OpenJDK), if not already installed (RHEL6)"
      ansible.builtin.package:
        name: "java-1.8.0-openjdk"
      when:
        - '"java-1.8.0-openjdk" not in ansible_facts.packages'
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version == '6'
    - name: "Install Java Development Kit (OpenJDK), if not already installed (RHEL7)"
      ansible.builtin.package:
        name: "java-latest-openjdk"
      when:
        - '"java-latest-openjdk" not in ansible_facts.packages'
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version == '7'
    - name: "Install Java Development Kit (OpenJDK), if not already installed (RHEL8)"
      ansible.builtin.package:
        name: "java-1.8.0-openjdk"
      when:
        - '"java-1.8.0-openjdk" not in ansible_facts.packages'
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version >= '8'

- name: "Find the JAVA_HOME from the host"
  shell: type -p java|xargs readlink -f|xargs dirname|xargs dirname
  register: shell

- name: "Set JAVA_HOME fact"
  ansible.builtin.set_fact:
    java_home: "{{ shell.stdout }}/bin/"

- name: "Create software directory under root homedir, if it does not exist"
  ansible.builtin.file:
    path: "/root/software/{{ package_name.split('.zip')[0] }}"
    state: directory

- name: "Download installer package from local repository"
  ansible.builtin.unarchive:
    src: "{{ software_url }}/{{ package_name }}"
    dest: "/root/software/{{ package_name.split('.zip')[0] }}"
    creates: "/root/software/{{ package_name.split('.zip')[0] }}/{{ package_name.split('.zip')[0] }}/install.sh"
    remote_src: yes
    validate_certs: no

- name: "Change the execute permissions of the installer script"
  ansible.builtin.file:
    path: "/root/software/{{ package_name.split('.zip')[0] }}/{{ package_name.split('.zip')[0] }}/install.sh"
    owner: root
    group: root
    mode: 0777
    state: file

- name: "Install Tidal Agent, if not already installed"
  block:
    - name: "Deploy expect install script"
      ansible.builtin.template:
        src: install.j2
        dest: "/root/software/{{ package_name.split('.zip')[0] }}/{{ package_name.split('.zip')[0] }}/script.exp"
        owner: root
        group: root
        mode: 0777
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version <= '7'
    - name: "Install Tidal Agent, if not already installed (RHEL7)"
      command: ./script.exp
      args:
        chdir: "/root/software/{{ package_name.split('.zip')[0] }}/{{ package_name.split('.zip')[0] }}/"
        creates: /opt/TIDAL/Agent/bin/tagent
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version <= '7'
    - name: "Install Tidal Agent, if not already installed (RHEL8)"
      ansible.builtin.expect:
        echo: yes
        command: ./install.sh
        chdir: "/root/software/{{ package_name.split('.zip')[0] }}/{{ package_name.split('.zip')[0] }}/"
        creates: /opt/TIDAL/Agent/bin/tagent
        responses:
          (.*)Continue to install(.*): "y"
          (.*)Which user should own the  files(.*): "root"
          (.*)Are these selections OK(.*): "y"
          (.*)Enter choice(.*): "q"
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version == '8'

- name: "Deploy Tidal Agent configuration .ini file"
  ansible.builtin.template:
    src: tagent.j2
    dest: /opt/TIDAL/Agent/bin/tagent.ini
    owner: root
    group: root
    mode: 0700

- name: "Tidal Agent Init Scripts"
  block:
    - name: "Deploy Tidal Agent init script (RHEL6)"
      ansible.builtin.template:
        src: initd.j2
        dest: /etc/init.d/tidal-agent
        owner: root
        group: root
        mode: 0755
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version <= '6'
    - name: "Deploy Tidal Agent init script (RHEL7+)"
      ansible.builtin.template:
        src: systemd.j2
        dest: /etc/systemd/system/tidal-agent.service
        owner: root
        group: root
        mode: 0644
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version >= '7'

- name: "Install and Enable Tidal Agent Init Scripts"
  ansible.builtin.service:
    name: "tidal-agent"
    enabled: yes
    state: restarted

- name: "Uninstall expect (RHEL7)"
  ansible.builtin.package:
    name: "expect"
    state: absent
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version <= '7'