---
# tasks file for ansible-role-tidal-agent

- name: "Include tasks from assert playbook"
  ansible.builtin.include_tasks: assert.yaml

- name: "Include tasks from lookup playbook"
  ansible.builtin.include_tasks: lookup.yaml

- name: "Include tasks from java playbook"
  ansible.builtin.include_tasks: java.yaml
  when:
    - java_installed is defined
    - not java_installed | bool

- name: "Include tasks from install playbook"
  ansible.builtin.include_tasks: install.yaml
  when:
    - install is defined
    - install | bool

#- name: "Include tasks from upgrade playbook"
#  ansible.builtin.include_tasks: upgrade.yaml
#  when:
#    - upgrade is defined
#    - upgrade | bool